// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAutobus.Database;

#nullable disable

namespace eAutobus.Migrations
{
    [DbContext(typeof(eAutobusi))]
    partial class eAutobusiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eAutobus.Database.Autobus", b =>
                {
                    b.Property<int>("AutobusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutobusID"), 1L, 1);

                    b.Property<int>("BrojAutobusa")
                        .HasColumnType("int");

                    b.Property<int>("BrojSjedista")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumProizvodnje")
                        .HasColumnType("datetime2");

                    b.Property<int>("GarazaID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Ispravan")
                        .HasColumnType("bit");

                    b.Property<string>("MarkaAutobusa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutobusID");

                    b.HasIndex("GarazaID");

                    b.ToTable("Autobus");

                    b.HasData(
                        new
                        {
                            AutobusID = 1,
                            BrojAutobusa = 6,
                            BrojSjedista = 55,
                            DatumProizvodnje = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(4653),
                            GarazaID = 1,
                            IsDeleted = false,
                            Ispravan = true,
                            MarkaAutobusa = "MAN"
                        },
                        new
                        {
                            AutobusID = 2,
                            BrojAutobusa = 10,
                            BrojSjedista = 55,
                            DatumProizvodnje = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(4752),
                            GarazaID = 2,
                            IsDeleted = false,
                            Ispravan = true,
                            MarkaAutobusa = "Volvo"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.AutobusVozac", b =>
                {
                    b.Property<int>("AutobusVozacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutobusVozacID"), 1L, 1);

                    b.Property<int>("AutobusID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Kraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<int>("Smjena")
                        .HasColumnType("int");

                    b.Property<int>("VozacID")
                        .HasColumnType("int");

                    b.HasKey("AutobusVozacID");

                    b.HasIndex("AutobusID");

                    b.HasIndex("VozacID");

                    b.ToTable("AutobusVozac");

                    b.HasData(
                        new
                        {
                            AutobusVozacID = 1,
                            AutobusID = 1,
                            IsDeleted = false,
                            Kraj = new DateTime(2023, 6, 1, 0, 30, 38, 827, DateTimeKind.Local).AddTicks(4791),
                            Pocetak = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(4787),
                            Smjena = 1,
                            VozacID = 1
                        },
                        new
                        {
                            AutobusVozacID = 2,
                            AutobusID = 2,
                            IsDeleted = false,
                            Kraj = new DateTime(2023, 6, 1, 0, 30, 38, 827, DateTimeKind.Local).AddTicks(4845),
                            Pocetak = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(4835),
                            Smjena = 1,
                            VozacID = 2
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Cjenovnik", b =>
                {
                    b.Property<int>("CjenovnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CjenovnikID"), 1L, 1);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OdredisteID")
                        .HasColumnType("int");

                    b.Property<int>("PolazisteID")
                        .HasColumnType("int");

                    b.Property<int>("TipkarteID")
                        .HasColumnType("int");

                    b.Property<int>("VrstaKarteID")
                        .HasColumnType("int");

                    b.Property<int>("ZonaID")
                        .HasColumnType("int");

                    b.HasKey("CjenovnikID");

                    b.HasIndex("OdredisteID");

                    b.HasIndex("PolazisteID");

                    b.HasIndex("TipkarteID");

                    b.HasIndex("VrstaKarteID");

                    b.HasIndex("ZonaID");

                    b.ToTable("Cjenovnik");

                    b.HasData(
                        new
                        {
                            CjenovnikID = 1,
                            Cijena = 5.0,
                            IsDeleted = false,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipkarteID = 1,
                            VrstaKarteID = 1,
                            ZonaID = 1
                        },
                        new
                        {
                            CjenovnikID = 2,
                            Cijena = 40.0,
                            IsDeleted = false,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipkarteID = 1,
                            VrstaKarteID = 2,
                            ZonaID = 1
                        },
                        new
                        {
                            CjenovnikID = 3,
                            Cijena = 8.0,
                            IsDeleted = false,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipkarteID = 2,
                            VrstaKarteID = 1,
                            ZonaID = 1
                        },
                        new
                        {
                            CjenovnikID = 4,
                            Cijena = 60.0,
                            IsDeleted = false,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipkarteID = 2,
                            VrstaKarteID = 2,
                            ZonaID = 1
                        },
                        new
                        {
                            CjenovnikID = 5,
                            Cijena = 6.0,
                            IsDeleted = false,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipkarteID = 3,
                            VrstaKarteID = 1,
                            ZonaID = 1
                        },
                        new
                        {
                            CjenovnikID = 6,
                            Cijena = 50.0,
                            IsDeleted = false,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipkarteID = 3,
                            VrstaKarteID = 2,
                            ZonaID = 1
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Garaza", b =>
                {
                    b.Property<int>("GarazaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarazaID"), 1L, 1);

                    b.Property<int>("BrojGaraze")
                        .HasColumnType("int");

                    b.Property<int>("BrojMjesta")
                        .HasColumnType("int");

                    b.Property<int>("GradID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopunjeno")
                        .HasColumnType("bit");

                    b.Property<string>("NazivGaraze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutnoAutobusa")
                        .HasColumnType("int");

                    b.HasKey("GarazaID");

                    b.HasIndex("GradID");

                    b.ToTable("Garaza");

                    b.HasData(
                        new
                        {
                            GarazaID = 1,
                            BrojGaraze = 1,
                            BrojMjesta = 10,
                            GradID = 1,
                            IsDeleted = false,
                            IsPopunjeno = false,
                            NazivGaraze = "Garaža-Mostar",
                            TrenutnoAutobusa = 1
                        },
                        new
                        {
                            GarazaID = 2,
                            BrojGaraze = 2,
                            BrojMjesta = 10,
                            GradID = 2,
                            IsDeleted = false,
                            IsPopunjeno = false,
                            NazivGaraze = "Garaža-Sarajevo",
                            TrenutnoAutobusa = 1
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Grad", b =>
                {
                    b.Property<int>("GradID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradID"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NazivGrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostanskiBroj")
                        .HasColumnType("int");

                    b.HasKey("GradID");

                    b.ToTable("Grad");

                    b.HasData(
                        new
                        {
                            GradID = 1,
                            IsDeleted = false,
                            NazivGrada = "Sarajevo",
                            PostanskiBroj = 88000
                        },
                        new
                        {
                            GradID = 2,
                            IsDeleted = false,
                            NazivGrada = "Mostar",
                            PostanskiBroj = 87000
                        },
                        new
                        {
                            GradID = 3,
                            IsDeleted = false,
                            NazivGrada = "Konjic",
                            PostanskiBroj = 88400
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Karta", b =>
                {
                    b.Property<int>("KartaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KartaID"), 1L, 1);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NacinPlacanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdredisteID")
                        .HasColumnType("int");

                    b.Property<int>("PolazisteID")
                        .HasColumnType("int");

                    b.Property<int>("TipKarteID")
                        .HasColumnType("int");

                    b.Property<int>("VrstaKarteID")
                        .HasColumnType("int");

                    b.HasKey("KartaID");

                    b.HasIndex("OdredisteID");

                    b.HasIndex("PolazisteID");

                    b.HasIndex("TipKarteID");

                    b.HasIndex("VrstaKarteID");

                    b.ToTable("Karta");

                    b.HasData(
                        new
                        {
                            KartaID = 1,
                            Cijena = 5.0,
                            IsDeleted = false,
                            NacinPlacanja = "Preuzećem",
                            OdredisteID = 1,
                            PolazisteID = 2,
                            TipKarteID = 1,
                            VrstaKarteID = 1
                        },
                        new
                        {
                            KartaID = 2,
                            Cijena = 10.0,
                            IsDeleted = false,
                            NacinPlacanja = "Online",
                            OdredisteID = 2,
                            PolazisteID = 1,
                            TipKarteID = 1,
                            VrstaKarteID = 2
                        });
                });

            modelBuilder.Entity("eAutobus.Database.KartaKupac", b =>
                {
                    b.Property<int>("KartaKupacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KartaKupacID"), 1L, 1);

                    b.Property<bool>("Aktivna")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumVadjenjaKarte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVazenjaKarte")
                        .HasColumnType("datetime2");

                    b.Property<int>("KartaID")
                        .HasColumnType("int");

                    b.Property<int>("KupacID")
                        .HasColumnType("int");

                    b.Property<bool>("Pravac")
                        .HasColumnType("bit");

                    b.Property<string>("PravacS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KartaKupacID");

                    b.HasIndex("KartaID");

                    b.HasIndex("KupacID");

                    b.ToTable("KartaKupac");

                    b.HasData(
                        new
                        {
                            KartaKupacID = 1,
                            Aktivna = true,
                            DatumVadjenjaKarte = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6091),
                            DatumVazenjaKarte = new DateTime(2023, 6, 1, 4, 30, 38, 827, DateTimeKind.Local).AddTicks(6100),
                            KartaID = 1,
                            KupacID = 1,
                            Pravac = true,
                            PravacS = "U jednom pravcu"
                        },
                        new
                        {
                            KartaKupacID = 2,
                            Aktivna = true,
                            DatumVadjenjaKarte = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6148),
                            DatumVazenjaKarte = new DateTime(2023, 6, 30, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6154),
                            KartaID = 2,
                            KupacID = 2,
                            Pravac = true,
                            PravacS = "U oba pravca"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisniciUlogeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisniciUlogeID"), 1L, 1);

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("UlogaID")
                        .HasColumnType("int");

                    b.HasKey("KorisniciUlogeID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("UlogaID");

                    b.ToTable("KorisniciUloge");

                    b.HasData(
                        new
                        {
                            KorisniciUlogeID = 1,
                            DatumIzmjene = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(5704),
                            KorisnikID = 1,
                            UlogaID = 1
                        },
                        new
                        {
                            KorisniciUlogeID = 2,
                            DatumIzmjene = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(5775),
                            KorisnikID = 2,
                            UlogaID = 2
                        },
                        new
                        {
                            KorisniciUlogeID = 3,
                            DatumIzmjene = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(5807),
                            KorisnikID = 3,
                            UlogaID = 2
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"), 1L, 1);

                    b.Property<string>("AdresaStanovanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogeID")
                        .HasColumnType("int");

                    b.HasKey("KorisnikID");

                    b.HasIndex("GradID");

                    b.HasIndex("UlogeID");

                    b.ToTable("Korisnik");

                    b.HasData(
                        new
                        {
                            KorisnikID = 1,
                            AdresaStanovanja = "Zalik BB",
                            BrojTelefona = "061222333",
                            DatumRodjenja = new DateTime(1995, 11, 1, 14, 29, 18, 167, DateTimeKind.Local).AddTicks(8190),
                            Email = "admin@gmail.com",
                            GradID = 2,
                            Ime = "Admin",
                            IsDeleted = false,
                            KorisnickoIme = "desktop",
                            LozinkaHash = "/VEfw6wmtify1fOTuLBJrXHXo0I=",
                            LozinkaSalt = "ZneRfhOqwq8zu13rCRCrIQ==",
                            Prezime = "Admin",
                            UlogeID = 1
                        },
                        new
                        {
                            KorisnikID = 2,
                            AdresaStanovanja = "Zalik BB",
                            BrojTelefona = "061444555",
                            DatumRodjenja = new DateTime(1995, 11, 1, 14, 29, 18, 167, DateTimeKind.Local).AddTicks(8190),
                            Email = "vozac1@gmail.com",
                            GradID = 2,
                            Ime = "Vozač1",
                            IsDeleted = false,
                            KorisnickoIme = "vozac1",
                            LozinkaHash = "/VEfw6wmtify1fOTuLBJrXHXo0I=",
                            LozinkaSalt = "ZneRfhOqwq8zu13rCRCrIQ==",
                            Prezime = "Vozač1",
                            UlogeID = 2
                        },
                        new
                        {
                            KorisnikID = 3,
                            AdresaStanovanja = "Dolina Sunca BB",
                            BrojTelefona = "061014555",
                            DatumRodjenja = new DateTime(1990, 10, 1, 14, 29, 18, 167, DateTimeKind.Local).AddTicks(8190),
                            Email = "vozac3@gmail.com",
                            GradID = 2,
                            Ime = "Vozač3",
                            IsDeleted = false,
                            KorisnickoIme = "vozac3",
                            LozinkaHash = "/VEfw6wmtify1fOTuLBJrXHXo0I=",
                            LozinkaSalt = "ZneRfhOqwq8zu13rCRCrIQ==",
                            Prezime = "Vozač3",
                            UlogeID = 3
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Kupac", b =>
                {
                    b.Property<int>("KupacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KupacID"), 1L, 1);

                    b.Property<string>("AdresaStanovanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KupacID");

                    b.ToTable("Kupac");

                    b.HasData(
                        new
                        {
                            KupacID = 1,
                            AdresaStanovanja = "Zalik BB",
                            BrojTelefona = "062333444",
                            Email = "kupac1@edu.fit.ba",
                            Ime = "Kupac1",
                            IsDeleted = false,
                            KorisnickoIme = "kupac1",
                            LozinkaHash = "/VEfw6wmtify1fOTuLBJrXHXo0I=",
                            LozinkaSalt = "ZneRfhOqwq8zu13rCRCrIQ==",
                            Prezime = "Kupac1"
                        },
                        new
                        {
                            KupacID = 2,
                            AdresaStanovanja = "Zalik BB",
                            BrojTelefona = "062333555",
                            Email = "kupac2@edu.fit.ba",
                            Ime = "Kupac2",
                            IsDeleted = false,
                            KorisnickoIme = "kupac2",
                            LozinkaHash = "/VEfw6wmtify1fOTuLBJrXHXo0I=",
                            LozinkaSalt = "ZneRfhOqwq8zu13rCRCrIQ==",
                            Prezime = "Kupac2"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.PlatiKartu", b =>
                {
                    b.Property<int>("PlatiKartuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatiKartuID"), 1L, 1);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumVadjenjaKarte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVazenjaKarte")
                        .HasColumnType("datetime2");

                    b.Property<bool>("JeLiPlacena")
                        .HasColumnType("bit");

                    b.Property<int>("KartaID")
                        .HasColumnType("int");

                    b.Property<int>("KupacID")
                        .HasColumnType("int");

                    b.HasKey("PlatiKartuID");

                    b.HasIndex("KartaID");

                    b.HasIndex("KupacID");

                    b.ToTable("PlatiKartu");

                    b.HasData(
                        new
                        {
                            PlatiKartuID = 1,
                            Cijena = 10.0,
                            DatumVadjenjaKarte = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6205),
                            DatumVazenjaKarte = new DateTime(2023, 6, 30, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6212),
                            JeLiPlacena = true,
                            KartaID = 2,
                            KupacID = 2
                        });
                });

            modelBuilder.Entity("eAutobus.Database.RasporedVoznje", b =>
                {
                    b.Property<int>("RasporedVoznjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RasporedVoznjeID"), 1L, 1);

                    b.Property<int>("AutobusID")
                        .HasColumnType("int");

                    b.Property<int>("BrojLinije")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalOcjena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KondukterID")
                        .HasColumnType("int");

                    b.Property<int>("OdredisteID")
                        .HasColumnType("int");

                    b.Property<int>("PolazisteID")
                        .HasColumnType("int");

                    b.Property<int>("VozacID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VrijemePolaska")
                        .HasColumnType("datetime2");

                    b.HasKey("RasporedVoznjeID");

                    b.HasIndex("AutobusID");

                    b.HasIndex("KondukterID");

                    b.HasIndex("OdredisteID");

                    b.HasIndex("PolazisteID");

                    b.HasIndex("VozacID");

                    b.ToTable("RasporedVoznje");

                    b.HasData(
                        new
                        {
                            RasporedVoznjeID = 1,
                            AutobusID = 1,
                            BrojLinije = 6,
                            Datum = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6345),
                            FinalOcjena = 5m,
                            IsDeleted = false,
                            KondukterID = 1,
                            OdredisteID = 2,
                            PolazisteID = 1,
                            VozacID = 1,
                            VrijemeDolaska = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6361),
                            VrijemePolaska = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6356)
                        },
                        new
                        {
                            RasporedVoznjeID = 2,
                            AutobusID = 2,
                            BrojLinije = 10,
                            Datum = new DateTime(2022, 3, 1, 14, 29, 18, 167, DateTimeKind.Local).AddTicks(8190),
                            FinalOcjena = 4m,
                            IsDeleted = false,
                            KondukterID = 2,
                            OdredisteID = 1,
                            PolazisteID = 2,
                            VozacID = 2,
                            VrijemeDolaska = new DateTime(2022, 3, 1, 14, 30, 0, 0, DateTimeKind.Local).AddTicks(8190),
                            VrijemePolaska = new DateTime(2022, 3, 1, 12, 15, 0, 0, DateTimeKind.Local).AddTicks(8190)
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Recenzija", b =>
                {
                    b.Property<int>("RecenzijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecenzijaID"), 1L, 1);

                    b.Property<DateTime>("DatumRecenzije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KupacID")
                        .HasColumnType("int");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("RasporedVoznjeID")
                        .HasColumnType("int");

                    b.Property<string>("VrstaUsluga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecenzijaID");

                    b.HasIndex("KupacID");

                    b.HasIndex("RasporedVoznjeID");

                    b.ToTable("Recenzija");

                    b.HasData(
                        new
                        {
                            RecenzijaID = 1,
                            DatumRecenzije = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6446),
                            Komentar = "Sve pohvale!",
                            KupacID = 1,
                            Ocjena = 5,
                            RasporedVoznjeID = 1,
                            VrstaUsluga = "Osoblje"
                        },
                        new
                        {
                            RecenzijaID = 2,
                            DatumRecenzije = new DateTime(2023, 5, 31, 16, 30, 38, 827, DateTimeKind.Local).AddTicks(6492),
                            Komentar = "Nije očišćeno!",
                            KupacID = 2,
                            Ocjena = 3,
                            RasporedVoznjeID = 2,
                            VrstaUsluga = "Vozilo"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Stanica", b =>
                {
                    b.Property<int>("StanicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StanicaID"), 1L, 1);

                    b.Property<int>("GradID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NazivLokacijeStanice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StanicaID");

                    b.HasIndex("GradID");

                    b.ToTable("Stanica");

                    b.HasData(
                        new
                        {
                            StanicaID = 1,
                            GradID = 1,
                            IsDeleted = false,
                            NazivLokacijeStanice = "Stanica-Sarajevo"
                        },
                        new
                        {
                            StanicaID = 2,
                            GradID = 2,
                            IsDeleted = false,
                            NazivLokacijeStanice = "Stanica-Mostar"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.TipKarte", b =>
                {
                    b.Property<int>("TipKarteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipKarteID"), 1L, 1);

                    b.Property<string>("Informacije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipKarteID");

                    b.ToTable("TipKarte");

                    b.HasData(
                        new
                        {
                            TipKarteID = 1,
                            Informacije = "Važi samo za studente uz priloženu potvrdu!",
                            IsDeleted = false,
                            Naziv = "Studentska"
                        },
                        new
                        {
                            TipKarteID = 2,
                            Informacije = "Važi samo za radnike uz priloženu potvrdu!",
                            IsDeleted = false,
                            Naziv = "Radnička"
                        },
                        new
                        {
                            TipKarteID = 3,
                            Informacije = "Važi samo za penzionere uz priloženu potvrdu!",
                            IsDeleted = false,
                            Naziv = "Penzionerska"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Uloge", b =>
                {
                    b.Property<int>("UlogeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogeID"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogeID");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            UlogeID = 1,
                            IsDeleted = false,
                            Naziv = "Admin",
                            Opis = "Admin ima pristup svemu."
                        },
                        new
                        {
                            UlogeID = 2,
                            IsDeleted = false,
                            Naziv = "Vozač",
                            Opis = "Vozač ima ograničen pristup."
                        },
                        new
                        {
                            UlogeID = 3,
                            IsDeleted = false,
                            Naziv = "Kondukter",
                            Opis = "Kondukter ima ograničen pristup."
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Vozac", b =>
                {
                    b.Property<int>("VozacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VozacID"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<string>("VozackaKategorija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VozacID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Vozac");

                    b.HasData(
                        new
                        {
                            VozacID = 1,
                            IsDeleted = false,
                            KorisnikID = 2,
                            VozackaKategorija = "B,C,D,D1"
                        },
                        new
                        {
                            VozacID = 2,
                            IsDeleted = false,
                            KorisnikID = 3,
                            VozackaKategorija = "B,C,D,D1"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.VrstaKarte", b =>
                {
                    b.Property<int>("VrstaKarteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrstaKarteID"), 1L, 1);

                    b.Property<string>("Informacije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VrstaKarteID");

                    b.ToTable("VrstaKarte");

                    b.HasData(
                        new
                        {
                            VrstaKarteID = 1,
                            Informacije = "Traje jedan dan!",
                            IsDeleted = false,
                            Naziv = "Dnevna"
                        },
                        new
                        {
                            VrstaKarteID = 2,
                            Informacije = "Traje jedan mjesec!",
                            IsDeleted = false,
                            Naziv = "Mjesečna"
                        },
                        new
                        {
                            VrstaKarteID = 3,
                            Informacije = "Traje jednu godinu!",
                            IsDeleted = false,
                            Naziv = "Godišnja"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Zona", b =>
                {
                    b.Property<int>("ZonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaID"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OznakaZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZonaID");

                    b.ToTable("Zona");

                    b.HasData(
                        new
                        {
                            ZonaID = 1,
                            IsDeleted = false,
                            OznakaZone = "Zona I"
                        },
                        new
                        {
                            ZonaID = 2,
                            IsDeleted = false,
                            OznakaZone = "Zona II"
                        },
                        new
                        {
                            ZonaID = 3,
                            IsDeleted = false,
                            OznakaZone = "Zona III"
                        });
                });

            modelBuilder.Entity("eAutobus.Database.Autobus", b =>
                {
                    b.HasOne("eAutobus.Database.Garaza", "Garaza")
                        .WithMany("Autobusi")
                        .HasForeignKey("GarazaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garaza");
                });

            modelBuilder.Entity("eAutobus.Database.AutobusVozac", b =>
                {
                    b.HasOne("eAutobus.Database.Autobus", "Autobus")
                        .WithMany("Vozaci")
                        .HasForeignKey("AutobusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Vozac", "Vozac")
                        .WithMany("Autobusi")
                        .HasForeignKey("VozacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autobus");

                    b.Navigation("Vozac");
                });

            modelBuilder.Entity("eAutobus.Database.Cjenovnik", b =>
                {
                    b.HasOne("eAutobus.Database.Stanica", "Odrediste")
                        .WithMany()
                        .HasForeignKey("OdredisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Stanica", "Polaziste")
                        .WithMany()
                        .HasForeignKey("PolazisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.TipKarte", "Tipkarte")
                        .WithMany()
                        .HasForeignKey("TipkarteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.VrstaKarte", "VrstaKarte")
                        .WithMany()
                        .HasForeignKey("VrstaKarteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odrediste");

                    b.Navigation("Polaziste");

                    b.Navigation("Tipkarte");

                    b.Navigation("VrstaKarte");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("eAutobus.Database.Garaza", b =>
                {
                    b.HasOne("eAutobus.Database.Grad", "Grad")
                        .WithMany("Garaze")
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("eAutobus.Database.Karta", b =>
                {
                    b.HasOne("eAutobus.Database.Stanica", "Odrediste")
                        .WithMany()
                        .HasForeignKey("OdredisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Stanica", "Polaziste")
                        .WithMany()
                        .HasForeignKey("PolazisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.TipKarte", "TipKarte")
                        .WithMany()
                        .HasForeignKey("TipKarteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.VrstaKarte", "VrstaKarte")
                        .WithMany()
                        .HasForeignKey("VrstaKarteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odrediste");

                    b.Navigation("Polaziste");

                    b.Navigation("TipKarte");

                    b.Navigation("VrstaKarte");
                });

            modelBuilder.Entity("eAutobus.Database.KartaKupac", b =>
                {
                    b.HasOne("eAutobus.Database.Karta", "Karta")
                        .WithMany("KupacList")
                        .HasForeignKey("KartaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Kupac", "Kupac")
                        .WithMany("KartaList")
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karta");

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("eAutobus.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eAutobus.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Uloge", "Uloga")
                        .WithMany()
                        .HasForeignKey("UlogaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eAutobus.Database.Korisnik", b =>
                {
                    b.HasOne("eAutobus.Database.Grad", "Grad")
                        .WithMany("Korisnici")
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Uloge", "Uloge")
                        .WithMany("Korisnik")
                        .HasForeignKey("UlogeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("Uloge");
                });

            modelBuilder.Entity("eAutobus.Database.PlatiKartu", b =>
                {
                    b.HasOne("eAutobus.Database.Karta", "Karta")
                        .WithMany("PlaceneKarte")
                        .HasForeignKey("KartaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Kupac", "Kupac")
                        .WithMany("PlaceneKarte")
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karta");

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("eAutobus.Database.RasporedVoznje", b =>
                {
                    b.HasOne("eAutobus.Database.Autobus", "Autobus")
                        .WithMany()
                        .HasForeignKey("AutobusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Vozac", "Kondukter")
                        .WithMany()
                        .HasForeignKey("KondukterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Stanica", "Odrediste")
                        .WithMany()
                        .HasForeignKey("OdredisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Stanica", "Polaziste")
                        .WithMany()
                        .HasForeignKey("PolazisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.Vozac", "Vozac")
                        .WithMany()
                        .HasForeignKey("VozacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autobus");

                    b.Navigation("Kondukter");

                    b.Navigation("Odrediste");

                    b.Navigation("Polaziste");

                    b.Navigation("Vozac");
                });

            modelBuilder.Entity("eAutobus.Database.Recenzija", b =>
                {
                    b.HasOne("eAutobus.Database.Kupac", "Kupac")
                        .WithMany("Recenzija")
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAutobus.Database.RasporedVoznje", "RasporedVoznje")
                        .WithMany("Recenzija")
                        .HasForeignKey("RasporedVoznjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kupac");

                    b.Navigation("RasporedVoznje");
                });

            modelBuilder.Entity("eAutobus.Database.Stanica", b =>
                {
                    b.HasOne("eAutobus.Database.Grad", "Grad")
                        .WithMany("Stanice")
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("eAutobus.Database.Vozac", b =>
                {
                    b.HasOne("eAutobus.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eAutobus.Database.Autobus", b =>
                {
                    b.Navigation("Vozaci");
                });

            modelBuilder.Entity("eAutobus.Database.Garaza", b =>
                {
                    b.Navigation("Autobusi");
                });

            modelBuilder.Entity("eAutobus.Database.Grad", b =>
                {
                    b.Navigation("Garaze");

                    b.Navigation("Korisnici");

                    b.Navigation("Stanice");
                });

            modelBuilder.Entity("eAutobus.Database.Karta", b =>
                {
                    b.Navigation("KupacList");

                    b.Navigation("PlaceneKarte");
                });

            modelBuilder.Entity("eAutobus.Database.Kupac", b =>
                {
                    b.Navigation("KartaList");

                    b.Navigation("PlaceneKarte");

                    b.Navigation("Recenzija");
                });

            modelBuilder.Entity("eAutobus.Database.RasporedVoznje", b =>
                {
                    b.Navigation("Recenzija");
                });

            modelBuilder.Entity("eAutobus.Database.Uloge", b =>
                {
                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eAutobus.Database.Vozac", b =>
                {
                    b.Navigation("Autobusi");
                });
#pragma warning restore 612, 618
        }
    }
}
